/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_wangduwei_demos_jni_JniCenter */

#ifndef _Included_com_example_wangduwei_demos_jni_JniCenter
#define _Included_com_example_wangduwei_demos_jni_JniCenter
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_wangduwei_demos_jni_JniCenter
 * Method:    getStringFromC
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_wangduwei_demos_jni_JniCenter_getStringFromC
  (JNIEnv *, jclass);

/*
 * Class:     com_example_wangduwei_demos_jni_JniCenter
 * Method:    changeArray
 * Signature: ([I)V
 */
JNIEXPORT void JNICALL Java_com_example_wangduwei_demos_jni_JniCenter_changeArray
  (JNIEnv *, jobject, jintArray);

JNIEXPORT jstring JNICALL
Java_com_example_wangduwei_demos_jni_JniCenter_getStringFromCObjectMethod(JNIEnv *env,
                                                                          jobject thiz) ;

JNIEXPORT jint JNICALL
Java_com_example_wangduwei_demos_jni_JniCenter_sumArray(JNIEnv *env, jobject thiz,
                                                        jintArray array) ;

JNIEXPORT jint JNICALL
Java_com_example_wangduwei_demos_jni_JniCenter_sumArray2(JNIEnv *env, jobject thiz,
                                                         jintArray array) ;

JNIEXPORT jobjectArray JNICALL
Java_com_example_wangduwei_demos_jni_JniCenter_initArrayInNative(JNIEnv *env, jclass clazz,
                                                                 jint size) ;

JNIEXPORT void JNICALL
Java_com_example_wangduwei_demos_jni_JniCenter_accessJavaField(JNIEnv *env, jobject thiz) ;

JNIEXPORT void JNICALL
Java_com_example_wangduwei_demos_jni_JniCenter_accessJavaStatisticField(JNIEnv *env, jobject thiz) ;

JNIEXPORT void JNICALL
Java_com_example_wangduwei_demos_jni_JniCenter_accessJavaField2(JNIEnv *env, jobject thiz) ;

#ifdef __cplusplus
}
#endif
#endif
